Add building from source with docker

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -1,28 +1,27 @@
 #!/bin/bash
 
 cd /opt/build/src
-if [ ! -f wekan-${WEKAN_RELEASE}.tar.gz ] ; then
-    curl https://releases.wekan.team/wekan-${WEKAN_RELEASE}.tar.gz -o wekan-${WEKAN_RELEASE}.tar.gz
+
+WEKAN_RELEASE=$(cat /opt/dist/WEKAN_RELEASE)
+
+echo "Wekan Release $WEKAN_RELEASE"
+
+if [ "$WEKAN_RELEASE" = "" ] ; then
+    echo "No WEKAN_RELEASE found. Aborting."
+    exit 1
 fi
 
-if [ ! -f wekan-${WEKAN_RELEASE}.tar.gz ] ; then
-    echo "wekan-${WEKAN_RELEASE}.tar.gz does not exists: aborting"
+if [ ! -f /opt/dist/wekan.tar.gz ] ; then
+    echo "/opt/dist/wekan.tar.gz does not exists: aborting"
     exit 1
 fi
 
 export WEKAN_DIR=$(pwd)
 
 rm -fR $WEKAN_DIR/bundle 2>/dev/null
-tar xzf wekan-$WEKAN_RELEASE.tar.gz || exit 1
-
-find $WEKAN_DIR/bundle/programs/server/node_modules/fibers/bin -name fibers.node | grep -v linux-x64 | while read f
-do
-    rm -f $f
-done
+tar xzf /opt/dist/wekan.tar.gz || exit 1
 
 cd $WEKAN_DIR
-
-find $WEKAN_DIR -name 'phantomjs' -type f -executable -print | xargs /bin/rm -f
 
 cp -vf /opt/node-v${NODE_RELEASE}-linux-x64/bin/node AppDir/usr/bin/
 strip -s AppDir/usr/bin/node
